export const ModuleList = [
	{
		name: "program_schools",
		label: "Programs and Schools",
	},
	{
		name: "students",
		label: "Student",
	},
	{
		name: "applications",
		label: "Application",
	},
	{
		name: "financial",
		label: "Financial",
	},
	{
		name: "generate_report",
		label: "Generate Reports",
	},
];

export const ModuleKeys = {
	Home: "home",
	ProgramAndSchool: "program_schools",
	Students: "students",
	Applications: "applications",
	Financial: "financial",
	GenerateReports: "generate_report",
	Interview: "interview",
	Support: "support",
};

export const Salutation = ["Mr.", "Ms.", "Mrs.", "Dr.", "Prof."];

export const StudentSource = [
	"Partner",
	"Internal",
	"Inbound",
	"Exhibition",
	"Sales",
	"Website",
	"Walk-in",
];

export const MaritalStatus = ["Married", "Unmarried", "Divorced"];

export const Gender = ["Male", "Female", "Other"];

export const Relationship = [
	"Father",
	"Mother",
	"Brother",
	"Sister",
	"Neighbour",
	"Relative",
	"Other",
];

export const SchoolTypes = [
	"Grade 12 , 12th Std , Higher Secondary , High School",
	"3 Year Diploma in Technical Education /Vocational",
	"1 Year Foundation at UK University or Pathway Provider",
	"Post Secondary Certificate [1 Year]",
	"3 Year Undergraduate Degree",
	"4 Year Undergraduate Degree",
	"Post Graduate Certificate",
	"Post Graduate Diploma",
	"Master Degree 1 or 2 Years",
	"Doctorate Degree",
	"Not Specified Above",
];

export const VisaOptions = [
	"No",
	"USA F1 VISA",
	"Canadian Study Permit or Visitor Visa",
	"UK Student Visa (Tier 4) or Short Term Study Visa",
	"Australian Study Visa",
];

export const EntityType = [
	"Public",
	"Private",
	"Proprietor",
	"Partnership",
	"Trust",
];

export const InterviewReasons = [
	"Onboarding Related",
	"Support",
	"Know The Platform",
];

export const DocumentStatus = {
	PENDING: "Pending",
	UPLOADED: "Uploaded",
	RE_UPLOADED: "Re-Uploaded",
	IN_REVIEW: "In Review",
	APPROVED: "Approved",
	CONDITIONALLY_APPROVED: "Conditionally Approved",
	REJECTED: "Rejected",
	REQUESTED: "Requested",
};

export const NotificationTypes = {
	Info: "Info",
	Rejected: "Rejected",
	Accepted: "Accepted",
	Attention: "Attention",
	Chat: "Chat",
	Announce: "Announce",
	Interview: "Interview",
	Payment: "Payment",
};

export const NotificationLabels = {
	student: "Student Notifications",
	comments: "Comments Notifications",
	commissions: "Commissions Notifications",
	agent: "Agent Notifications",
	case: "Case Notifications",
	invoice: "Invoice Notifications",
	application: "Application Notifications",
	payments: "Payment Notifications",
	schools: "Schools Notifications",
	intake: "Intake Notifications",
	document: "Document Notifications",
};

export const ApplicationStatus = [
	"New",
	"Accepted",
	"Program Closed",
	"Withdrawn",
	"Cancelled",
	"Not Paid",
];

export const Disciplines = [
	"Performing arts",
	"Visual Arts",
	"History",
	"Languages and Literature",
	"Law",
	"Philosophy",
	"Religious Studies",
	"Theology",
	"Anthropology",
	"Archaeology",
	"Geography",
	"Political Science",
	"Psychology",
	"Economics",
	"Social work",
	"Sociology",
	"Biology",
	"Chemistry",
	"Earth Science",
	"Astronomy",
	"Physics",
	"Computer Science",
	"Mathematics - Pure Mathematics",
	"Mathematics - Applied Mathematics",
	"Agriculture",
	"Architecture and design",
	"Business",
	"Divinity",
	"Education",
	"Chemical Engineering",
	"Mechanical Engineering",
	"Civil Engineering",
	"System science",
	"Educational Technology",
	"Electrical Engineering",
	"Materials Science and Engineering",
	"Environmental Studies and Forestry",
	"Family and Consumer Science",
	"Human physical performance and recreation",
	"Journalism,Media Studies and Communication",
	"Library and museum studies",
	"Medicine and Health",
	"Military sciences",
	"Public administration",
	"Public policy",
	"Social Work",
	"Transportation",
];

export const SubDisciplines = {
	"Performing arts": ["Music", "Dance", "Television", "Theatre", "Film"],
	"Visual Arts": ["Fashion", "Applied arts", "Fine arts"],
	History: [
		"African history",
		"American history",
		"Ancient history",
		"Asian history",
		"Australian history",
		"Cultural history",
		"Ecclesiastical history of the Catholic Church",
		"Economic history",
		"Environmental history",
		"European history",
		"Intellectual history",
		"Jewish history",
		"Latin American history",
		"Modern history",
		"Philosophical history",
		"Political history",
		"Pre-Columbian era history",
		"Prehistory",
		"Public history",
		"Russian history",
		"Scientific history",
		"Technological history",
		"World history",
	],
	"Languages and Literature": [
		"Linguistics",
		"Comics studies",
		"Comparative literature",
		"Creative writing",
		"English literature",
		"History of literature",
		"Literary theory",
		"Poetry",
		"Prose",
		"World literature",
	],
	Law: [
		"Administrative law",
		"Canon law",
		"Civil law",
		"Comparative law",
		"Criminal law",
		"Constitutional law",
		"Jewish law",
		"Islamic law",
		"Substantive law",
		"Jurisprudence",
		"Legal management (academic discipline)",
		"Procedural law",
		"Competition law",
		"Legal management (academic discipline)",
		"Administrative law",
		"Canon law",
		"Comparative law",
		"Constitutional law",
		"Competition law",
		"Criminal law",
		"Islamic law",
		"Jewish law (outline)",
		"Jurisprudence (Philosophy of Law)",
		"Civil law",
		"Law enforcement (outline)",
		"Procedural law",
		"Substantive law",
	],
	Philosophy: [
		"Aesthetics",
		"Applied philosophy",
		"Epistemology",
		"Ethics",
		"Logic",
		"Meta-philosophy",
		"Metaphysics",
		"Philosophical traditions and schools",
		"Social philosophy and political philosophy",
	],
	"Religious Studies": [
		"History of Religion",
		"Anthropology of Religion",
		"Sociology of Religion",
		"Psychology of Religion",
		"Phenomenology of Religion",
	],
	Theology: [
		"Biblical studies",
		"Buddhist theology",
		"Christian theology",
		"Hindu theology",
		"Jewish theology",
	],
	Anthropology: [
		"Muslim theology",
		"Linguistic anthropology",
		"Cultural anthropology",
		"Social anthropology",
	],
	Archaeology: [
		"Biocultural anthropology",
		"Evolutionary anthropology",
		"Feminist archaeology",
		"Forensic anthropology",
		"Maritime archaeology",
		"Palaeoanthropology",
	],
	Geography: [
		"Physical geography",
		"Human geography",
		"Integrated geography",
		"Cartography",
	],
	"Political Science": [
		"American politics",
		"Canadian politics",
		"Civics",
		"Comparative politics",
		"European studies",
		"Geopolitics",
		"International relations",
		"International organizations",
		"Nationalism studies",
		"Peace and conflict studies",
		"Policy studies",
		"Political behavior",
		"Political culture",
		"Political economy",
		"Political history",
		"Political philosophy",
		"Public administration",
		"Public law",
		"Psephology",
		"Social choice theory",
		"Singapore politics",
	],
	Psychology: [
		"Abnormal psychology",
		"Applied psychology",
		"Biological psychology",
		"Clinical neuropsychology",
		"Clinical psychology",
		"Cognitive psychology",
		"Community psychology",
		"Comparative psychology",
		"Conservation psychology",
		"Consumer psychology",
		"Counseling psychology",
		"Criminal psychology",
		"Cultural psychology",
		"Developmental psychology",
		"Differential psychology",
		"Ecological psychology",
		"Educational psychology",
		"Environmental psychology",
		"Evolutionary psychology",
		"Experimental psychology",
		"Group psychology",
		"Family psychology",
		"Feminine psychology",
		"Forensic developmental psychology",
		"Forensic psychology",
		"Health psychology",
		"Humanistic psychology",
		"Indigenous psychology",
		"Legal psychology",
		"Mathematical psychology",
		"Media psychology",
		"Medical psychology",
		"Military psychology",
		"Moral psychology and Descriptive ethics",
		"Music psychology",
		"Neuropsychology",
		"Occupational health psychology",
		"Occupational psychology",
		"Organizational psychology (a.k.a., Industrial Psychology)",
		"Parapsychology (outline)",
		"Pediatric psychology",
		"Pedology (children study)",
		"Personality psychology",
		"Phenomenology",
		"Political psychology",
		"Positive psychology",
		"Psychoanalysis",
		"Psychobiology",
		"Psychology of religion",
		"Psychopathology",
		"Psychometrics",
		"Psychophysics",
		"Quantitative psychology",
		"Rehabilitation psychology",
		"School psychology",
		"Social psychology",
		"Sport psychology",
		"Traffic psychology",
		"Transpersonal psychology",
	],
	Economics: [
		"Agricultural economics",
		"Anarchist economics",
		"Applied economics",
		"Behavioural economics",
		"Bioeconomics",
		"Complexity economics",
		"Computational economics",
		"Consumer economics",
		"Development economics",
		"Ecological economics",
		"Econometrics",
		"Economic geography",
		"Economic sociology",
		"Economic systems",
		"Education economics",
		"Energy economics",
		"Entrepreneurial economics",
		"Environmental economics",
		"Evolutionary economics",
		"Experimental economics",
		"Feminist economics",
		"Financial econometrics",
		"Financial economics",
		"Green economics",
		"Growth economics",
		"Human development theory",
		"Industrial organization",
		"Information economics",
		"Institutional economics",
		"International economics",
		"Islamic economics",
		"Labor economics",
		"Law and economics",
		"Macroeconomics",
		"Managerial economics",
		"Marxian economics",
		"Mathematical economics",
		"Microeconomics",
		"Monetary economics",
		"Neuroeconomics",
		"Participatory economics",
		"Political economy",
		"Public economics",
		"Public finance",
		"Real estate economics",
		"Resource economics",
		"Social choice theory",
		"Socialist economics",
		"Socioeconomics",
		"Transport economics",
		"Welfare economics",
	],
	"Social work": [
		"Clinical social work",
		"Community practice",
		"Mental health",
		"Psychosocial rehabilitation",
		"Person-centered therapy",
		"Family therapy",
		"Financial social work",
	],
	Sociology: [
		"Analytical sociology",
		"Applied sociology",
		"Architectural sociology",
		"Area studies",
		"Asian studies",
		"Behavioral sociology",
		"Collective behavior",
		"Community informatics",
		"Comparative sociology",
		"Conflict theory",
		"Criminology/Criminal justice (outline)",
		"Critical management studies",
		"Critical sociology",
		"Cultural sociology",
		"Cultural studies/ethnic studies",
		"Demography/Population",
		"Digital sociology",
		"Dramaturgical sociology",
		"Economic sociology",
		"Educational sociology",
		"Empirical sociology",
		"Environmental sociology",
		"Evolutionary sociology",
		"Feminist sociology",
		"Figurational sociology",
		"Futures studies (outline)",
		"Gender studies",
		"Historical sociology",
		"Human ecology",
		"Humanistic sociology",
		"Industrial sociology",
		"Interactionism",
		"Interpretive sociology",
		"Jealousy sociology",
		"Macrosociology",
		"Marxist sociology",
		"Mathematical sociology",
		"Medical sociology",
		"Mesosociology",
		"Microsociology",
		"Military sociology",
		"Natural resource sociology",
		"Organizational studies",
		"Phenomenological sociology",
		"Policy sociology",
		"Psychoanalytic sociology",
		"Science studies/Science and technology studies",
		"Sexology",
		"Social capital",
		"Social change",
		"Social conflict theory",
		"Social control",
		"Social economy",
		"Social philosophy",
		"Social policy",
		"Social psychology",
		"Social stratification",
		"Social theory",
		"Social transformation",
		"Sociobiology",
		"Sociocybernetics",
		"Sociolinguistics",
		"Sociology of aging",
		"Sociology of agriculture",
		"Sociology of art",
		"Sociology of autism",
		"Sociology of childhood",
		"Sociology of conflict",
		"Sociology of culture",
		"Sociology of cyberspace",
		"Sociology of development",
		"Sociology of deviance",
		"Sociology of disaster",
		"Sociology of education",
		"Sociology of emotions",
		"Sociology of fatherhood",
		"Sociology of finance",
		"Sociology of food",
		"Sociology of gender",
		"Sociology of generations",
		"Sociology of globalization",
		"Sociology of government",
		"Sociology of health and illness",
		"Sociology of human consciousness",
		"Sociology of immigration",
		"Sociology of knowledge",
		"Sociology of language",
		"Sociology of law",
		"Sociology of leisure",
		"Sociology of literature",
		"Sociology of markets",
		"Sociology of marriage",
		"Sociology of motherhood",
		"Sociology of music",
		"Sociology of natural resources",
		"Sociology of organizations",
		"Sociology of peace, war, and social conflict",
		"Sociology of punishment",
		"Sociology of race and ethnic relations",
		"Sociology of religion",
		"Sociology of risk",
		"Sociology of science",
		"Sociology of scientific knowledge",
		"Sociology of social change",
		"Sociology of social movements",
		"Sociology of space",
		"Sociology of sport",
		"Sociology of technology",
		"Sociology of terrorism",
		"Sociology of the body",
		"Sociology of the family",
		"Sociology of the history of science",
		"Sociology of the Internet",
		"Sociology of work",
		"Sociomusicology",
		"Structural sociology",
		"Theoretical sociology",
		"Urban studies or Urban sociology/Rural sociology",
		"Victimology",
		"Visual sociology",
	],
	Biology: [
		"Aerobiology",
		"Anatomy",
		"Biochemistry (outline)",
		"Bioinformatics",
		"Biophysics (outline)",
		"Biotechnology (outline)",
		"Botany (outline)",
		"Cell biology (outline)",
		"Chronobiology",
		"Computational biology",
		"Cryobiology",
		"Developmental biology",
		"Ecology",
		"Endocrinology",
		"Epigenetics",
		"Ethnobiology",
		"Evolutionary biology",
		"Genetics (outline)",
		"Histology",
		"Human biology",
		"Immunology (outline)",
		"Limnology",
		"Linnaean taxonomy",
		"Marine biology",
		"Mathematical biology",
		"Microbiology",
		"Molecular biology",
		"Mycology",
		"Neuroscience (outline)",
		"Nutrition (outline)",
		"Paleobiology",
		"Parasitology",
		"Pathology",
		"Physiology",
		"Structural Biology",
		"Systematics (Taxonomy)",
		"Systems biology",
		"Virology",
		"Xenobiology",
		"Zoology (outline)",
	],
	Chemistry: [
		"Agrochemistry",
		"Analytical chemistry",
		"Astrochemistry",
		"Atmospheric chemistry",
		"Biochemistry (outline)",
		"Chemical biology",
		"Chemical engineering (outline)",
		"Cheminformatics",
		"Computational chemistry",
		"Cosmochemistry",
		"Electrochemistry",
		"Environmental chemistry",
		"Femtochemistry",
		"Flavor",
		"Flow chemistry",
		"Geochemistry",
		"Green chemistry",
		"Histochemistry",
		"Hydrogenation",
		"Immunochemistry",
		"Inorganic chemistry",
		"Marine chemistry",
		"Mathematical chemistry",
		"Mechanochemistry",
		"Medicinal chemistry",
		"Molecular biology",
		"Molecular mechanics",
		"Nanotechnology",
		"Natural product chemistry",
		"Neurochemistry",
		"Oenology",
		"Organic chemistry (outline)",
		"Organometallic chemistry",
		"Petrochemistry",
		"Pharmacology",
		"Photochemistry",
		"Physical chemistry",
		"Physical organic chemistry",
		"Phytochemistry",
		"Polymer chemistry",
		"Quantum chemistry",
		"Radiochemistry",
		"Solid-state chemistry",
		"Sonochemistry",
		"Supramolecular chemistry",
		"Surface chemistry",
		"Synthetic chemistry",
		"Theoretical chemistry",
		"Thermochemistry",
	],
	"Earth Science": [
		"Edaphology",
		"Environmental chemistry",
		"Environmental science",
		"Gemology",
		"Geochemistry",
		"Geodesy",
		"Physical geography (outline)",
		"Geophysics (outline)",
		"Paleontology",
	],
	Astronomy: [
		"Astrobiology",
		"Observational astronomy",
		"Astrophysics",
		"Cosmology",
		"Interstellar medium",
		"Numerical simulations",
		"Stellar astrophysics",
		"Planetary science",
	],
	Physics: [
		"Acoustics",
		"Aerodynamics",
		"Applied physics",
		"Astrophysics",
		"Atomic, molecular, and optical physics",
		"Biophysics (outline)",
		"Computational physics",
		"Condensed matter physics",
		"Cryogenics",
		"Electricity",
		"Electromagnetism",
		"Elementary particle physics",
		"Experimental physics",
		"Fluid dynamics",
		"Geophysics (outline)",
		"Mathematical physics",
		"Mechanics",
		"Medical physics",
		"Molecular physics",
		"Newtonian dynamics",
		"Nuclear physics",
		"Optics",
		"Plasma physics",
		"Quantum physics",
		"Solid mechanics",
		"Solid state physics",
		"Statistical mechanics",
		"Theoretical physics",
		"Thermal physics",
		"Thermodynamics",
	],
	"Computer Science": [
		"Logic in computer science",
		"Algorithms",
		"Artificial intelligence",
		"Data structures",
		"Computer architecture",
		"Computer graphics",
		"Computer communications (networks)",
		"Computer security and reliability",
		"Computing in mathematics, natural sciences, engineering, and medicine",
		"Computing in social sciences, arts, humanities, and professions",
		"Distributed computing",
		"Human-computer interaction",
		"Operating systems",
		"Parallel computing",
		"Programming languages",
		"Quantum computing",
		"Software engineering",
		"Theory of computation",
		"VLSI design",
	],
	"Mathematics - Pure Mathematics": [
		"Mathematical logic and Foundations of mathematics",
		"Algebra (outline)",
		"Analysis",
		"Probability theory",
		"Geometry (outline) and Topology",
		"Number theory",
	],
	"Mathematics - Applied Mathematics": [
		"Approximation theory",
		"Combinatorics (outline)",
		"Cryptography",
		"Dynamical systems",
		"Game theory",
		"Graph theory",
		"Information theory",
		"Mathematical physics",
		"Numerical analysis",
		"Operations research",
		"Statistics (outline)",
		"Theory of computation",
	],
	Agriculture: [
		"Aeroponics",
		"Agroecology",
		"Agrology",
		"Agronomy",
		"Animal husbandry (Animal science)",
		"Anthroponics",
		"Agricultural economics",
		"Agricultural engineering",
		"Aquaculture",
		"Aquaponics",
		"Enology",
		"Entomology",
		"Fogponics",
		"Food science",
		"Forestry",
		"Horticulture",
		"Hydrology (outline)",
		"Hydroponics",
		"Pedology",
		"Plant science (outline)",
		"Pest control",
		"Purification",
		"Viticulture",
	],
	"Architecture and design": [
		"Architecture",
		"Architectural analytics",
		"Historic preservation",
		"Interior design (interior architecture)",
		"Landscape architecture (landscape planning)",
		"Landscape design",
		"Urban planning (urban design)",
		"Visual communication",
		"Industrial design (product design)",
		"User experience design",
		"Decorative arts",
		"Fashion design",
		"Textile design",
	],
	Business: [
		"Accounting",
		"Business administration",
		"Business analysis",
		"Business ethics",
		"Business law",
		"Business management",
		"E-Business",
		"Entrepreneurship",
		"Finance (outline)",
		"Industrial and labor relations",
		"Information systems (Business informatics)",
		"Information technology (outline)",
		"International trade",
		"Management (outline)",
		"Marketing (outline)",
		"Operations management",
		"Purchasing",
		"Risk management and insurance",
		"Systems science",
	],
	Divinity: [
		"Canon law",
		"Church history",
		"Field ministry",
		"Hermeneutics",
		"Scriptural study and languages",
		"Theology (outline)",
	],
	Education: [
		"Comparative education",
		"Critical pedagogy",
		"Curriculum and instruction",
		"Educational leadership",
		"Educational philosophy",
		"Educational psychology",
		"Educational technology",
		"Distance education",
	],
	"Chemical Engineering": [
		"Bioengineering",
		"Catalysis",
		"Materials engineering",
		"Molecular engineering",
		"Nanotechnology",
		"Polymer engineering",
		"Process design",
		"Process engineering",
		"Reaction engineering",
		"Thermodynamics",
		"Transport phenomena",
	],
	"Mechanical Engineering": [
		"Aerospace engineering",
		"Acoustical engineering",
		"Automotive engineering",
		"Biomedical engineering",
		"Continuum mechanics",
		"Fluid mechanics",
		"Heat transfer",
		"Industrial engineering",
		"Manufacturing engineering",
		"Marine engineering",
		"Mass transfer",
		"Mechatronics",
		"Nanoengineering",
		"Ocean engineering",
		"Optical engineering",
		"Robotics",
		"Thermodynamics",
	],
	"Civil Engineering": [
		"Coastal engineering",
		"Earthquake engineering",
		"Ecological engineering",
		"Environmental engineering",
		"Geotechnical engineering",
		"Hydraulic engineering",
		"Mining engineering",
		"Transportation engineering",
		"Structural engineering",
		"Structural mechanics",
		"Surveying",
	],
	"System science": [
		"Chaos theory",
		"Complex systems",
		"Conceptual systems",
		"Control theory",
		"Cybernetics",
		"Network science",
		"Operations research",
		"Systems biology",
		"System dynamics",
		"Systems ecology",
		"Systems engineering",
		"Systems psychology",
		"Systems theory",
		"Systems theory in anthropology",
	],
	"Educational Technology": [
		"Instructional design",
		"Human performance technology",
		"Knowledge management",
	],
	"Electrical Engineering": [
		"Applied physics",
		"Computer engineering (outline)",
		"Computer science",
		"Control systems engineering",
		"Electronic engineering",
		"Engineering physics",
		"Information theory",
		"Mechatronics",
		"Power engineering",
		"Quantum computing",
		"Robotics (outline)",
		"Semiconductors",
		"Telecommunications engineering",
	],
	"Materials Science and Engineering": [
		"Biomaterials",
		"Ceramic engineering",
		"Crystallography",
		"Nanomaterials",
		"Photonics",
		"Physical Metallurgy",
		"Polymer engineering",
		"Polymer science",
		"Semiconductors",
	],
	"Environmental Studies and Forestry": [
		"Environmental management",
		"Environmental policy",
		"Wildlife observation",
		"Recreation ecology",
		"Silviculture",
		"Sustainability studies",
		"Toxicology",
		"Ecology",
	],
	"Family and Consumer Science": [
		"Consumer education",
		"Housing",
		"Interior design",
		"Nutrition (outline)",
		"Textiles",
	],
	"Human physical performance and recreation": [
		"Biomechanics / Sports biomechanics",
		"Sports coaching",
		"Escapology",
		"Ergonomics",
		"Physical fitness",
		"Game design",
		"Exercise physiology",
		"Kinesiology / Exercise physiology / Performance science",
		"Leisure studies",
		"Navigation",
		"Outdoor activity",
		"Physical activity",
		"Physical education / Pedagogy",
		"Sociology of sport",
		"Sexology",
		"Sports / exercise",
		"Sports journalism / sportscasting",
		"Sport management",
		"Sport psychology",
		"Sports medicine",
		"Survival skills",
		"Toy and amusement design",
	],
	"Journalism,Media Studies and Communication": [
		"Journalism (outline)",
		"Media studies (Mass media)",
		"Narratology",
		"Communication studies",
	],
	"Library and museum studies": [
		"Archival science",
		"Archivist",
		"Bibliographic databases",
		"Bibliometrics",
		"Bookmobile",
		"Cataloging",
		"Categorization",
		"Classification",
		"Collections care",
		"Collection management",
		"Collection Management Policy",
		"Conservation science",
		"Conservation and restoration of cultural heritage",
		"Curator",
		"Data storage",
		"Database management",
		"Data modeling",
		"Digital preservation",
		"Dissemination",
		"Film preservation",
		"Five laws of library science",
		"Historic preservation",
		"History of library science",
		"Human-computer interaction",
		"Indexer",
		"Informatics",
		"Information architecture",
		"Information broker",
		"Information literacy",
		"Information retrieval",
		"Information science (outline)",
		"Information systems and technology",
		"Integrated library system",
		"Interlibrary loan",
		"Knowledge engineering",
		"Knowledge management",
		"Library",
		"Library binding",
		"Library circulation",
		"Library instruction",
		"Library portal",
		"Library technical services",
		"Management",
		"Mass deacidification",
		"Museology",
		"Museum education",
		"Object conservation",
		"Preservation",
		"Prospect research",
		"Readers' advisory",
		"Records management",
		"Reference",
		"Reference desk",
		"Reference management software",
		"Registrar",
		"Research methods",
		"Slow fire",
		"Special library",
		"Statistics",
	],
	"Medicine and Health": [
		"Alternative medicine",
		"Audiology",
		"Clinical laboratory sciences/Clinical pathology/Laboratory medicine",
		"Clinical physiology",
		"Dentistry (outline)",
		"Dermatology",
		"Emergency medicine (outline)",
		"Epidemiology",
		"Geriatrics",
		"Gynaecology",
		"Health informatics/Clinical informatics",
		"Hematology",
		"Holistic medicine",
		"Infectious disease",
		"Intensive care medicine",
		"Internal medicine",
		"Medical toxicology",
		"Music therapy",
		"Nursing",
		"Nutrition (outline) and dietetics",
		"Obstetrics (outline)",
		"Occupational hygiene",
		"Occupational therapy",
		"Occupational toxicology",
		"Ophthalmology",
		"Optometry",
		"Otolaryngology",
		"Pathology",
		"Pediatrics",
		"Pharmaceutical sciences",
		"Physical fitness",
		"Physical therapy",
		"Physiotherapy",
		"Podiatry",
		"Preventive medicine",
		"Primary care",
		"Psychiatry (outline)",
		"Psychology (outline)",
		"Public health",
		"Radiology",
		"Recreational therapy",
		"Rehabilitation medicine",
		"Respiratory therapy",
		"Sleep medicine",
		"Speech–language pathology",
		"Sports medicine",
		"Surgery",
		"Traditional medicine",
		"Urology",
		"Veterinary medicine",
	],
	"Military sciences": [
		"Amphibious warfare",
		"Artillery",
		"Battlespace",
		"Campaigning",
		"Military engineering",
		"Doctrine",
		"Espionage",
		"Game theory",
		"Grand strategy",
		"Leadership",
		"Logistics",
		"Military operation",
		"Military history",
		"Military intelligence",
		"Military law",
		"Military medicine",
		"Naval science",
		"Organization",
		"Strategy",
		"Tactics",
		"Military weapons",
		"Other Military",
	],
	"Public administration": [
		"Civil service",
		"Corrections",
		"Conservation biology",
		"Criminal justice (outline)",
		"Disaster research",
		"Disaster response",
		"Emergency management",
		"Emergency services",
		"Fire safety (Structural fire protection)",
		"Fire ecology (Wildland fire management)",
		"Governmental affairs",
		"International affairs",
		"Law enforcement",
		"Peace and conflict studies",
		"Police science",
		"Policy studies",
		"Public administration",
		"Public safety",
		"Public service",
	],
	"Public policy": [
		"Agricultural policy",
		"Commercial policy",
		"Cultural policy",
		"Domestic policy",
		"Drug policy",
		"Economic policy",
		"Education policy",
		"Energy policy",
		"Environmental policy",
		"Food policy",
		"Foreign policy",
		"Health policy",
		"Housing policy",
		"Immigration policy",
		"Knowledge policy",
		"Language policy",
		"Military policy",
		"Science policy",
		"Security policy",
		"Social policy",
		"Public policy by country",
	],
	"Social Work": [
		"Child welfare",
		"Community practice",
		"Human Services",
		"Child welfare",
		"Community practice",
		"Community organizing",
		"Social policy",
		"Human Services",
		"Corrections",
		"Gerontology",
		"Medical social work",
		"Mental health",
		"School social work",
	],
	Transportation: [
		"Highway safety",
		"Infographics",
		"Intermodal transportation studies",
		"Logistics",
		"Marine transportation",
		"Operations research",
		"Mass transit",
		"Travel",
		"Vehicles",
	],
};
